// Generated by the Maven Archetype Plug-in
package br.com.doit.multitenant.app;

import er.extensions.appserver.ERXSession;

/**
 * @author <a href="mailto:hprange@gmail.com">Henrique Prange</a>
 */
@SuppressWarnings("serial")
public class Session extends ERXSession
{
	public Session()
	{
		super();
	}
}
